id: PB64AB180
initial_creation_type: input
source_metadata:
  title: Middle Way Series
  language: bo
  description: 'The following texts are available as part of our series on the Middle
    Way (Madhyamaka/Mādhyamika; dbu ma) philosophy:'
  volume:
    c3e07e8fe8164d4890db09393d31aa33:
      title: Conveying the Essence of the Middle Way of Consequence
      parent: General
    b7c040827526448daeb4a7b32d77f45e:
      title: 'The Words of Candra: The Definitive Secret of the Great Middle Way of
        Consequence Beyond Extremes, the Fundamental Intent of All the Tathāgatas'
      parent: General
    eecbd5145d674aef84b546d92c63c086:
      title: 'The Seed of Reasoning: Notes on the Five Great Logical Arguments of
        the Middle Way'
      parent: General
    3d1bfd88e1fa40ee9ba3e83d2f340ad6:
      title: A Step-by-Step Meditation on the Definitive Meaning of the Great Middle
        Way
      parent: General
    2b7096d99d9a4e1ea28f0a7275624096:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      parent: General
    09c1084b8ae2485c8bcd5e60a5e2d125:
      title: Profound Instruction on the View of the Middle Way
      parent: General
    95f557aa573c4896b4d43b66c46984d3:
      title: 'Clarifying the Essence: A Summary of the Instructions on the View of
        the Middle Way'
      parent: General
    e6c3521982dc4d90a61d09f111a71296:
      title: Commentary on the Madhyamakāvatāra—Part 1—Collection of Reasoning
      parent: Madhyamakāvatāra
    be506c948e50472fa2e8855c47c9b38c:
      title: Commentary on the Madhyamakāvatāra—Part 2—Title and Translators Homage
      parent: Madhyamakāvatāra
    c098c61f19734117979da42813ca4a5d:
      title: Prologue to Introduction to the Middle Way (Madhyamakāvatāra)
      parent: Madhyamakāvatāra
    83b4c9d4a8e04639acd189a0cc9ec302:
      title: Concise Middle Way Aspiration
      parent: Prayers
    be4059e376ae43f29ab6a48106e9bbae:
      title: Middle Way Aspiration
      parent: Prayers
created_at: '2022-03-01T04:42:52.489659'
last_modified_at: '2022-03-01T04:42:52.489662'
